### ISSUE TITLE
Suggestion - Easier commands adding

### ISSUE THREAD

**Issue by Bang1338** [WlodekM/textmode-term-sp#1]
Instead of putting every single command in `comamnds.ts`, make a folder called `commands` and only thing you can do is just adding `curl.ts`. `commands.ts` will handle them.

**Comment by WlodekM** [comment]
that would be hard to do because in web you cant just do a fs.readdir on the /commands directory, but i could theoretically do an array of command names and make it import them from their files

gonna add that to my todo list (and unlike the other stuff there this will be easier (hopefully))
